---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hub.austrianopensciencecloud.org
  resources:
  - profiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.austrianopensciencecloud.org
  resources:
  - profiles/finalizers
  verbs:
  - update
- apiGroups:
  - hub.austrianopensciencecloud.org
  resources:
  - profiles/status
  verbs:
  - get
  - patch
  - update
