## Needed for Hub to retrieve Profile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: jupyterhub
    component: hub
  name: hub-profiles
  namespace: jupyter
rules:
- apiGroups:
  - "hub.austrianopensciencecloud.org"
  resources:
  - profiles
  verbs:
  - get
  - watch
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: jupyterhub
    component: hub
  name: hub-profiles
  namespace: jupyter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hub-profiles
subjects:
- kind: ServiceAccount
  name: hub
  namespace: jupyter

## Change this accordingly
---
apiVersion: v1
kind: List
items: 
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      name: grader-1cpu-2gram
    spec: 
      slug: grader-1cpu-2gram
      allowed_groups:
        - admin
        - instructor
      display_name: "Python with Grader Service: 1 CPU core & 2GB RAM"
      description: "You will have a Python Kernel installed and the grader service enabled."
      kubespawner_override:
        image: ghcr.io/tu-wien-datalab/grader-service-labextension:latest
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      name: base-notebook-1cpu-2gram
    spec: 
      slug: base-notebook-1cpu-2gram
      allowed_groups:
        - lect1:instructor
        - lect1:tutor
        - lect1:student
      display_name: "Python: 1 CPU core & 2GB RAM"
      description: "You will have a Python Kernel installed."
      kubespawner_override:
        image: jupyter/base-notebook:lab-3.4.3
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      name: cpp-notebook-1cpu-2gram
    spec: 
      slug: cpp-notebook-1cpu-2gram
      display_name: "C++: 1 CPU core & 2GB RAM"
      description: "You will have a C++ Kernel installed."
      kubespawner_override:
        image: adlsregistrysbx.azurecr.io/jupyter/cpp-notebook:latest
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      name: r-notebook-1cpu-2gram
    spec: 
      slug: r-notebook-1cpu-2gram
      display_name: "R: 1 CPU core & 2GB RAM"
      description: "You will have a R Kernel installed."
      kubespawner_override:
        image: adlsregistrysbx.azurecr.io/jupyter/r-notebook:latest
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      name: pokeball-notebook
    spec: 
      slug: pokeball-notebook
      allowed_groups:
        - lect1:instructor
      display_name: "Pokeballs!!"
      description: "highly dangerous, use with care"
      profile_options:
        image:
          display_name: Image
          choices:
            v0.0.1:
              display_name: Pokeballs v0.0.1
              kubespawner_override:
                image: adlsregistrysbx.azurecr.io/pokeball/fortran:0.0.1
            v0.0.2:
              display_name: Pokeballs v0.0.2
              kubespawner_override:
                image: adlsregistrysbx.azurecr.io/pokeball/fortran:0.0.2
            v0.0.3:
              display_name: Pokeballs v0.0.3
              kubespawner_override:
                image: adlsregistrysbx.azurecr.io/pokeball/fortran:0.0.3
        ressources:
          display_name: Ressources
          choices:
            '2':
              display_name: 2 vCPU & 2G Memory
              kubespawner_override:
                cpu_limit: 2
                mem_limit: 2G
            '4':
              display_name: 4 vCPU & 4G Memory
              kubespawner_override:
                cpu_limit: 4
                mem_limit: 4G
            '6':
              display_name: 6 vCPU & 6G Memory
              kubespawner_override:
                cpu_limit: 6
                mem_limit: 6G
