apiVersion: v1
items: 
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      generateName: profile-sample-
    spec: 
      display_name: Python DataScience
      slug: datascience-small
      profile_options:
        memory:
          display_name: CPUs
          choices:
            '2':
              display_name: 2 CPUs
              kubespawner_override:
                cpu_limit: 2
                cpu_guarantee: 1
            '4':
              display_name: 4 CPUs
              kubespawner_override:
                cpu_limit: 4
                cpu_guarantee: 1
      kubespawner_override:
        image: ghcr.io/tu-wien-datalab/grader-service-labextension:latest
  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      generateName: profile-sample-
    spec: 
      display_name: DataScience - Medium instance (GPUx2)
      slug: datascience-gpu2x
      kubespawner_override:
        image: ghcr.io/tu-wien-datalab/grader-service-labextension:latest
        cpu_limit: 2
        mem_limit: 2G

  - apiVersion: hub.austrianopensciencecloud.org/v1alpha1
    kind: Profile
    metadata:
      generateName: profile-sample-
    spec:
      display_name: Training Env
      slug: training-python
      profile_options:
        image:
          display_name: Image
          choices:
            pytorch:
              display_name: Python 3 Training Notebook
              kubespawner_override:
                image: ghcr.io/tu-wien-datalab/grader-service-labextension:latest
            tf:
              display_name: R 4.2 Training Notebook
              kubespawner_override:
                image: ghcr.io/tu-wien-datalab/grader-service-labextension:latest
        memory:
          display_name: CPUs
          choices:
            '2':
              display_name: 2 CPUs
              kubespawner_override:
                cpu_limit: 2
                cpu_guarantee: 1
            '4':
              display_name: 4 CPUs
              kubespawner_override:
                cpu_limit: 4
                cpu_guarantee: 1
      kubespawner_override:
        cpu_limit: 8
        mem_limit: 8G
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
